name: Deploy to Cloudflare Workers with Wrangler

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - name: print secrets
      run: |
          echo "$WRANGLER_TOML" >> doesitarm-default/wrangler.toml
          cat doesitarm-default/wrangler.toml
    - uses: actions/checkout@master
    - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'doesitarm-default'
